package com.github.zzave.teambalance.api.domain.model

import java.util.UUID

/**
 * The identity of a [Position]. Same shape and the same edges-only conversion as [EventId], which
 * documents the pattern.
 *
 * No `random()` factory: a position's identity is generated by the persistence adapter when the row
 * is created, so the domain only ever reads one.
 */
@JvmInline
value class PositionId(val value: UUID) {
    override fun toString(): String = value.toString()
}
