/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WelcomeIndexRouteImport } from './routes/welcome/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as MembersIndexRouteImport } from './routes/members/index'
import { Route as TeamSettingsRouteImport } from './routes/team/settings'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as EventsEventIdRouteImport } from './routes/events/$eventId'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeIndexRoute = WelcomeIndexRouteImport.update({
  id: '/welcome/',
  path: '/welcome/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIndexRoute = MembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamSettingsRoute = TeamSettingsRouteImport.update({
  id: '/team/settings',
  path: '/team/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/team/settings': typeof TeamSettingsRoute
  '/members/': typeof MembersIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/welcome/': typeof WelcomeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/team/settings': typeof TeamSettingsRoute
  '/members': typeof MembersIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/welcome': typeof WelcomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/team/settings': typeof TeamSettingsRoute
  '/members/': typeof MembersIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/welcome/': typeof WelcomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/auth/verify'
    | '/events/$eventId'
    | '/invite/$token'
    | '/team/settings'
    | '/members/'
    | '/profile/'
    | '/welcome/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/auth/verify'
    | '/events/$eventId'
    | '/invite/$token'
    | '/team/settings'
    | '/members'
    | '/profile'
    | '/welcome'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/auth/verify'
    | '/events/$eventId'
    | '/invite/$token'
    | '/team/settings'
    | '/members/'
    | '/profile/'
    | '/welcome/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  InviteTokenRoute: typeof InviteTokenRoute
  TeamSettingsRoute: typeof TeamSettingsRoute
  MembersIndexRoute: typeof MembersIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  WelcomeIndexRoute: typeof WelcomeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome/': {
      id: '/welcome/'
      path: '/welcome'
      fullPath: '/welcome/'
      preLoaderRoute: typeof WelcomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/': {
      id: '/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/settings': {
      id: '/team/settings'
      path: '/team/settings'
      fullPath: '/team/settings'
      preLoaderRoute: typeof TeamSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  InviteTokenRoute: InviteTokenRoute,
  TeamSettingsRoute: TeamSettingsRoute,
  MembersIndexRoute: MembersIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  WelcomeIndexRoute: WelcomeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
