/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminCreationCodesRouteImport } from './routes/admin/creation-codes'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as CreateTeamIndexRouteImport } from './routes/create-team/index'
import { Route as EventsEventIdRouteImport } from './routes/events/$eventId'
import { Route as GetStartedIndexRouteImport } from './routes/get-started/index'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as MembersIndexRouteImport } from './routes/members/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as OnboardingJoinRouteImport } from './routes/onboarding/join'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as TeamIndexRouteImport } from './routes/team/index'
import { Route as TeamSettingsRouteImport } from './routes/team/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCreationCodesRoute = AdminCreationCodesRouteImport.update({
  id: '/admin/creation-codes',
  path: '/admin/creation-codes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateTeamIndexRoute = CreateTeamIndexRouteImport.update({
  id: '/create-team/',
  path: '/create-team/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedIndexRoute = GetStartedIndexRouteImport.update({
  id: '/get-started/',
  path: '/get-started/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIndexRoute = MembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingJoinRoute = OnboardingJoinRouteImport.update({
  id: '/onboarding/join',
  path: '/onboarding/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIndexRoute = TeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamSettingsRoute = TeamSettingsRouteImport.update({
  id: '/team/settings',
  path: '/team/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/creation-codes': typeof AdminCreationCodesRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/onboarding/join': typeof OnboardingJoinRoute
  '/team/settings': typeof TeamSettingsRoute
  '/create-team/': typeof CreateTeamIndexRoute
  '/get-started/': typeof GetStartedIndexRoute
  '/members/': typeof MembersIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/team/': typeof TeamIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/creation-codes': typeof AdminCreationCodesRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/onboarding/join': typeof OnboardingJoinRoute
  '/team/settings': typeof TeamSettingsRoute
  '/create-team': typeof CreateTeamIndexRoute
  '/get-started': typeof GetStartedIndexRoute
  '/members': typeof MembersIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/team': typeof TeamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/creation-codes': typeof AdminCreationCodesRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/onboarding/join': typeof OnboardingJoinRoute
  '/team/settings': typeof TeamSettingsRoute
  '/create-team/': typeof CreateTeamIndexRoute
  '/get-started/': typeof GetStartedIndexRoute
  '/members/': typeof MembersIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/team/': typeof TeamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/creation-codes'
    | '/auth/verify'
    | '/events/$eventId'
    | '/invite/$token'
    | '/onboarding/join'
    | '/team/settings'
    | '/create-team/'
    | '/get-started/'
    | '/members/'
    | '/onboarding/'
    | '/profile/'
    | '/team/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/creation-codes'
    | '/auth/verify'
    | '/events/$eventId'
    | '/invite/$token'
    | '/onboarding/join'
    | '/team/settings'
    | '/create-team'
    | '/get-started'
    | '/members'
    | '/onboarding'
    | '/profile'
    | '/team'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin/creation-codes'
    | '/auth/verify'
    | '/events/$eventId'
    | '/invite/$token'
    | '/onboarding/join'
    | '/team/settings'
    | '/create-team/'
    | '/get-started/'
    | '/members/'
    | '/onboarding/'
    | '/profile/'
    | '/team/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminCreationCodesRoute: typeof AdminCreationCodesRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  InviteTokenRoute: typeof InviteTokenRoute
  OnboardingJoinRoute: typeof OnboardingJoinRoute
  TeamSettingsRoute: typeof TeamSettingsRoute
  CreateTeamIndexRoute: typeof CreateTeamIndexRoute
  GetStartedIndexRoute: typeof GetStartedIndexRoute
  MembersIndexRoute: typeof MembersIndexRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  TeamIndexRoute: typeof TeamIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/creation-codes': {
      id: '/admin/creation-codes'
      path: '/admin/creation-codes'
      fullPath: '/admin/creation-codes'
      preLoaderRoute: typeof AdminCreationCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-team/': {
      id: '/create-team/'
      path: '/create-team'
      fullPath: '/create-team/'
      preLoaderRoute: typeof CreateTeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started/': {
      id: '/get-started/'
      path: '/get-started'
      fullPath: '/get-started/'
      preLoaderRoute: typeof GetStartedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/': {
      id: '/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/join': {
      id: '/onboarding/join'
      path: '/onboarding/join'
      fullPath: '/onboarding/join'
      preLoaderRoute: typeof OnboardingJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/': {
      id: '/team/'
      path: '/team'
      fullPath: '/team/'
      preLoaderRoute: typeof TeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/settings': {
      id: '/team/settings'
      path: '/team/settings'
      fullPath: '/team/settings'
      preLoaderRoute: typeof TeamSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminCreationCodesRoute: AdminCreationCodesRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  InviteTokenRoute: InviteTokenRoute,
  OnboardingJoinRoute: OnboardingJoinRoute,
  TeamSettingsRoute: TeamSettingsRoute,
  CreateTeamIndexRoute: CreateTeamIndexRoute,
  GetStartedIndexRoute: GetStartedIndexRoute,
  MembersIndexRoute: MembersIndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  TeamIndexRoute: TeamIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
